// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV-yESZnqkKBNCGlhGbeF8dAXCRupUNUk',
    appId: '1:734223310633:android:f71781049af3e0da6de138',
    messagingSenderId: '734223310633',
    projectId: 'clean-campus-78c4a',
    databaseURL: 'https://clean-campus-78c4a-default-rtdb.firebaseio.com',
    storageBucket: 'clean-campus-78c4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYJYfKVboQnxH15113EUa7eE_K_0gMZg8',
    appId: '1:734223310633:ios:c05d565a0deacc2d6de138',
    messagingSenderId: '734223310633',
    projectId: 'clean-campus-78c4a',
    databaseURL: 'https://clean-campus-78c4a-default-rtdb.firebaseio.com',
    storageBucket: 'clean-campus-78c4a.appspot.com',
    androidClientId: '734223310633-nhjglv5a8906qlmvrnq2is730fdp0991.apps.googleusercontent.com',
    iosClientId: '734223310633-de94n56eba59foe1k8ph1pofjmfertjt.apps.googleusercontent.com',
    iosBundleId: 'com.cleancityworker.app',
  );
}
